### ISSUE TITLE
ValueError: Supported target types are: ('binary', 'multiclass'). Got 'unknown' instead.

### ISSUE THREAD

**Issue by aminzadenoori** [danielelic/deep-casas#2]
Hi,
when I want to run "train.py --v lstm" I have this error, ValueError: Supported target types are: ('binary', 'multiclass'). Got 'unknown' instead.
can you guide me on how to fix it?
thank you.

**Comment by aminzadenoori** [comment]
I solved that by:

from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()
y = label_encoder.fit_transform(target_labels)

**Comment by mahmoudaghvami** [comment]
I found the same error.
the line 38 of train.py raise the error
line 38           for train, test in kfold.split(X, Y) 
The error       ValueError: Supported target types are: ('binary', 'multiclass'). Got 'unknown' 

apprently Y is unknown

the fix by [aminzadenoori] does not work for me

**Comment by zendra123** [comment]
> 

Hi @mahmoudaghvami I have the same error, have you found any solution, how to fix this?

**Comment by xiaoluobie** [comment]
I had the same problem:ValueError: Supported target types are: (‘binary‘, ‘multiclass‘). Got ‘unknown‘ instead.”, and now it's over.

You can try adding a code：` y = y.ype (float)` in front of this line of code：`for fold_num, (train_index, test_index) in enumerate(skf.split(X, y)):`

See my blog for detailed solutions and reasons.The CSDN address link is：
[CSDN](https://blog.csdn.net/m0_45521766/article/details/129072631?spm=1001.2014.3001.5501)

I hope this is helpful
@mahmoudaghvami  @zendra123

**Comment by zendra123** [comment]
@xiaoluobie thank you.
